### ISSUE TITLE
Define and implement a flow for sending logs to us in case of an error

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/hiuvi#141]
A user should be able to send us the logs in case he faces an error.

- [ ] Make the logger write to a file
- [ ] Verify there is a global exception handler that logs exceptions
- [ ] Add to the readme a description of how to send logs (either manual or automatic)
- [ ] Make sure we printing things to the log alongside the UI (scraping events, for example)
- [ ] Make sure we are re-assigning the console.log function, or we linting to not use it and use our custom logger instead.

**Comment by baruchiro** [comment]
Also

 - Make sure we printing things to the log alongside the UI (scraping events, for example)

**Comment by baruchiro** [comment]
OK, I refreshed my memory about our logging infrastructure.

We have two tools, [`electron-log`](https://www.npmjs.com/package/electron-log) and *Sentry*.
When I'm thinking about logging implementation, I'm very careful about sending all the logs automatically and do whatever we want, because I don't want to accidentally send sensitive information.

For now, the practice is logging to a local file, and I turned off all the auto logging in *Sentry*, and I'm using it just to manually send us a report (this is not my purpose for the future, it is just a minimal requirement.)

About the logger, we initialize it in the *main process*, and passing it to the *renderer*. Because it writes to one file, so it has to be one object.

From that point we just need to update the infra, inject the logger and *Sentry* in a more convenient way, and with types, and so on.

TYDW?

BTW @brafdlog I need to give you access to *Sentry*.

**Comment by brafdlog** [comment]
Sounds good.

How about overriding console log (https://github.com/megahertz/electron-log#overriding-consolelog) so the code can just use conosle.log and it will work

**Comment by baruchiro** [comment]
I remembering this feature, but I didn't use it, maybe it not worked?

Anyway, I thought about that again, and maybe we want to keep it without the `console.log`. In that way, you can still debug with `console.log`, but `eslint` will catch you 8f you accidentally committed a dummy log write.

**Comment by baruchiro** [comment]
Consider using a different logger for `background.ts` and `main.ts`, see https://github.com/megahertz/electron-log/issues/244.
