### ISSUE TITLE
Make the ci of master publish a release and have a download link we can use

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/hiuvi#154]
In order to publish the app to people we need to have a downloadable link.

For that we would like the ci of the master branch to publish a release to latest so we can have a link that always points to the latest artifact for installing the app.

**Comment by baruchiro** [comment]
Why? You have a really good Releases feature here in Github.

See in my old project: https://github.com/baruchiro/israeli-bank-scrapers-desktop/releases

There is also a very simple API:

https://github.com/baruchiro/israeli-bank-scrapers-desktop/blob/d6e3c9a803dd2cc53898e56da6a051044a8459fe/nuxt/components/DownloadButton.vue#L102-L125

The code is a little complicated because I wanted to get the link for the latest `pre-release` release. If you don't want to get the `pre-release`, you can use `latest` and things go simpler.

**Comment by brafdlog** [comment]
Cool. So we need to set that up. Updating the description

**Comment by baruchiro** [comment]
OK, please talk to me before you're taking this task.
This process should be already implemented.
It's also implemented semi-automatic by Electron-Builder. See [`.github/workflows/release.yml`](https://github.com/brafdlog/budget-tracking/blob/unifyRepos/.github/workflows/release.yml)

**Comment by baruchiro** [comment]
Closed, it working
