### ISSUE TITLE
In CSV and JSON exporter settings use a ui file picker instead of text field to choose where to save the file

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/hiuvi#155]

**Comment by baaraak** [comment]
Hi
I started to work on this issue and I have some questions about how should I continue this...
Work in progress:
https://github.com/baaraak/hiuvi/commit/ddafbbb1975fb4313cf0ac3cb04de17e3cd37a9f
![Screen Shot 2021-06-05 at 22 23 41](https://user-images.githubusercontent.com/16448454/120903159-3346ee00-c64d-11eb-94a4-dc253eaf3d4c.png)
So the only way to let the user select a folder is using electron native dialog.
At first, I thought to use the `<input type="file" webkitdirectory />` but it's not recommended and can lead to different bugs. (I also tested it)
[Read more](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory)

Background.ts: https://github.com/baaraak/hiuvi/commit/ddafbbb1975fb4313cf0ac3cb04de17e3cd37a9f#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291f
To open the dialog we should trigger an event from the electron main process.
I thought maybe there is a nicer way to add these handlers to `background.js`,
First I thought to change the `'choose-dir'` key to TS enum constant and maybe separate the `ipcMain.handle` to a different file, like `handlers.ts`.
This file will be responsible to register all the event handlers for electron

CsvExporter: https://github.com/baaraak/hiuvi/commit/ddafbbb1975fb4313cf0ac3cb04de17e3cd37a9f#diff-e7af9e850b9bf9f5a4b28ef8b5abb00958fde041449aff6497aaeb2e2c40c504
Here I struggled a little bit with the `v-model` attribute and how it works, maybe you could help me.
I added the `click:append` to call `openNativeDialog()` method that trigger the `'choose-dir'` handler from `background.ts` and get the selected folder path in `filePath` (I will rename this var).
Then I'm trying to trigger the input `change` event so the `filePath` in the store will be updated but it's not working.
I tried also to set the input `value` attribute to the `filePath` state from data but it's still not dispatch the event 
The submit button stays disabled but even if I remove this disabled attr it's still not working.
I'm sure there is an elegant way to do it I'm just not familiar enough with vue.js

Let me know ho do you want me to continue

**Comment by baruchiro** [comment]
Hi, thanks a lot!

I will look on it later. But since you wrote some code and you mention it, consider to open a PR so you will be able to comment on the code.

**Comment by baruchiro** [comment]
I @baaraak !
First, I liked your change!

- You're right, we need to create a "nicer way" to register handlers on IPC. My approach is not to think too much about the future, since the code is always changing. Instead, I'm doing just one step forward.  
 the only thing I can think about it right now is to create a dedicated file (or two) to register the event handlers, all of them in one place. And maybe another file for send those events (instead of [require the `ipcRenderer` from a Vue file](https://github.com/baaraak/hiuvi/commit/ddafbbb1975fb4313cf0ac3cb04de17e3cd37a9f#diff-e7af9e850b9bf9f5a4b28ef8b5abb00958fde041449aff6497aaeb2e2c40c504R32)).
- About `click:append`, you did it right, but according to the [docs](https://vuetifyjs.com/en/components/text-fields/#icon-events), this event is only for the `icon`. I think if we are using a file chooser now, we don't need to support manual typing, consider just use `@click`, or even another component (without text input?).    
 BTW, for the whole change, did you checked the [`v-file-input`](https://vuetifyjs.com/en/components/file-inputs/)?
- About the `v-model` and so, there are few points here, I will try to put some, but please talk with me and we can discuss 1X1.  
   1. We are using *Vue v2*, but with a port of *V3*, called `@vue/composition-api`. With this, we can define most of the component logic inside the `setup` method. There we declaring all the `computed`/`reactive` variables.
   1. In this `setup` method, since most of the *Exporters* are with the same logic, we moved all their shared implementation into one place:
 https://github.com/brafdlog/hiuvi/blob/dce503b1d375c16b69faafd4470289fb5d8a03b8/src/ui/components/app/exporters/exportersCommon.ts#L7-L25  
  You can see that our "Exporters Forms" are not completely reactive. I mean, the form model is **cloned** from the store, so you can change the exporter config, but it will update the store only when you clicking on the **save**.  
  To make your change, you need to update the `exporter` that declared in that shared method. (You need to get it in the `setup` method and create a function for that.... please talk with me if you need help).


Hope I helped. Good Luck!

**Comment by baaraak** [comment]
Great, thank you so much for the explanation... I will keep working on that and let you know.
BTW, I tested the `v-file-input` which render an input with a `type="file"`, this is not working as expected...
It's selecting all the files recursively from inside the selected directory
If you select you `Downloads` folder, the `e.target.files` will contain all the files that exist in `Downloads` folder and you don't have any way to know for sure which folder/file the user selected...

I also looked at some different electron open source apps and it seems everyone using electron native dialog to get folder path.

**Comment by baaraak** [comment]
Hi, So I hope that I understood what you meant 😁, I create a PR you can take a lot...
I'm not sure that the handlers registration/initialization is what you meant but we still have 2 "bugs"

1. The user can't enter filePath manually, so basically it's mean that he can't control the generated filename the default is `'transaction.csv' || 'transaction.json'`.
It's ok with you? Also, when the dialog is opened and the user selects a directory path, I get only the path and the file name `'transaction.csv'` is removed.
a. We can add the filename manually something like `filePath = filePath + '/'transaction.csv''`.
b. We can do what I did in the start with the input + icon, then the user can select a path by clicking on the icon and using the dialog and editing it/change the filename.
c. We can let the user choose 1 filename in a central place and all the exporter will use this file name

2. The json/csv component, I wrote it in here: https://github.com/brafdlog/hiuvi/pull/253/files#diff-e7af9e850b9bf9f5a4b28ef8b5abb00958fde041449aff6497aaeb2e2c40c504R75
